### ISSUE TITLE
API 17 lunching error 

### ISSUE THREAD

**Issue by forotan1** [JarvanMo/ExoPlayerVideoView#13]
i just added the player on project but after releasing version 2.0.0 i saw what i was searching for its playing the stream in different quality.
but this version of exo player show this error in while lunching in API 17 which is minimum sdk version of my project 
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jarvanmo.demo/com.jarvanmo.demo.SimpleVideoViewActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class com.jarvanmo.exoplayerview.ui.ExoVideoView
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.jarvanmo.exoplayerview.ui.ExoVideoView
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                     at com.jarvanmo.demo.SimpleVideoViewActivity.onCreate(SimpleVideoViewActivity.java:46)
                                                     at android.app.Activity.performCreate(Activity.java:5104)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                     at com.jarvanmo.demo.SimpleVideoViewActivity.onCreate(SimpleVideoViewActivity.java:46) 
                                                     at android.app.Activity.performCreate(Activity.java:5104) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class TextView
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                     at com.jarvanmo.exoplayerview.ui.ExoVideoPlaybackControlView.<init>(ExoVideoPlaybackControlView.java:337)
                                                     at com.jarvanmo.exoplayerview.ui.ExoVideoView.<init>(ExoVideoView.java:248)
                                                     at com.jarvanmo.exoplayerview.ui.ExoVideoView.<init>(ExoVideoView.java:125)
                                                     at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                     at com.jarvanmo.demo.SimpleVideoViewActivity.onCreate(SimpleVideoViewActivity.java:46) 
                                                     at android.app.Activity.performCreate(Activity.java:5104) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_error_outline_white_48dp.xml from drawable resource ID #0x7f060067
                                                     at android.content.res.Resources.loadDrawable(Resources.java:1953)
                                                     at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
                                                     at android.widget.TextView.<init>(TextView.java:754)
                                                     at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:76)
                                                     at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72)
                                                     at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                     at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1016)
                                                     at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1073)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                     at com.jarvanmo.exoplayerview.ui.ExoVideoPlaybackControlView.<init>(ExoVideoPlaybackControlView.java:337) 
                                                     at com.jarvanmo.exoplayerview.ui.ExoVideoView.<init>(ExoVideoView.java:248) 
                                                     at com.jarvanmo.exoplayerview.ui.ExoVideoView.<init>(ExoVideoView.java:125) 
                                                     at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                     at com.jarvanmo.demo.SimpleVideoViewActivity.onCreate(SimpleVideoViewActivity.java:46) 
                                                     at android.app.Activity.performCreate(Activity.java:5104) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: org.xmlpull.v1.XmlPullParserException: Binar

**Comment by JarvanMo** [comment]
@forotan1 problem solved.please update to 2.0.1

**Comment by JarvanMo** [comment]
@forotan1 problem so

**Comment by forotan1** [comment]
thanks a lot its solved.
