### ISSUE TITLE
Video player error

### ISSUE THREAD

**Issue by iashishagrawaljpr** [JarvanMo/ExoPlayerVideoView#19]
Not able to play video on android 4.4. please look into this

http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

**Comment by JarvanMo** [comment]
@iashishagrawaljpr I can't play this link on VLC,either. Check this video please.

**Comment by iashishagrawaljpr** [comment]
Sorry for late reply. i was out of station so couldn't check this.
But this video is being played by Exo Player directly. https://github.com/google/ExoPlayer/

**Comment by iashishagrawaljpr** [comment]
Below is the error Log:

07-13 10:56:40.357 3418-3432/com.jarvanmo.demo E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.queueInputBuffer(Native Method)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:764)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)



URL: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4

This is working on android 26

**Comment by JarvanMo** [comment]
do you run on an emulator or a phone?

**Comment by iashishagrawaljpr** [comment]
I tried on phone & emulator both.

**Comment by iashishagrawaljpr** [comment]
@JarvanMo : I am facing another issue of Audio & Video out of sync.
could you please give me some guidance how to resolve both issues
thanks in advance
