### ISSUE TITLE
在观看视频的时候，home退出到手机桌面，再进入，就会报错，点击开始暂停无效

### ISSUE THREAD

**Issue by FLYANDHEIGHT** [JarvanMo/ExoPlayerVideoView#25]

**Comment by JarvanMo** [comment]
我目前还没发现这样的问题。错误信息？机型？

**Comment by FLYANDHEIGHT** [comment]
魅族note3 7.0

**Comment by FLYANDHEIGHT** [comment]
Could not get codec capabilities
    java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at android.media.MediaCodecInfo$CodecCapabilities.<init>(MediaCodecInfo.java:915)
        at android.media.MediaCodecInfo$CodecCapabilities.<init>(MediaCodecInfo.java:866)
        at android.media.MediaCodecList.getCodecCapabilities(Native Method)
        at android.media.MediaCodecList.getNewCodecInfoAt(MediaCodecList.java:111)
        at android.media.MediaCodecList.initCodecList(MediaCodecList.java:87)
        at android.media.MediaCodecList.<init>(MediaCodecList.java:170)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.ensureMediaCodecInfosInitialized(MediaCodecUtil.java:589)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.getCodecCount(MediaCodecUtil.java:567)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:239)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:150)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:126)
        at com.google.android.exoplayer2.mediacodec.MediaCodecSelector$1.getDecoderInfo(MediaCodecSelector.java:34)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.supportsFormat(MediaCodecVideoRenderer.java:239)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:300)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:439)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:345)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:162)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:143)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1507)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)
08-27 22:17:50.807 6148-6179/com.jarvanmo.demo E/MediaCodecList: Could not get codec capabilities
    java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at android.media.MediaCodecInfo$CodecCapabilities.<init>(MediaCodecInfo.java:915)
        at android.media.MediaCodecInfo$CodecCapabilities.<init>(MediaCodecInfo.java:866)
        at android.media.MediaCodecList.getCodecCapabilities(Native Method)
        at android.media.MediaCodecList.getNewCodecInfoAt(MediaCodecList.java:111)
        at android.media.MediaCodecList.initCodecList(MediaCodecList.java:87)
        at android.media.MediaCodecList.<init>(MediaCodecList.java:170)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.ensureMediaCodecInfosInitialized(MediaCodecUtil.java:589)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.getCodecCount(MediaCodecUtil.java:567)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:239)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:150)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:126)
        at com.google.android.exoplayer2.mediacodec.MediaCodecSelector$1.getDecoderInfo(MediaCodecSelector.java:34)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.supportsFormat(MediaCodecVideoRenderer.java:239)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:300)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:439)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:345)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:162)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:143)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1507)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)
08-27 22:17:50.809 6148-6179/com.jarvanmo.demo E/MediaCodecList: Could not get codec capabilities
    java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at android.media.MediaCodecInfo$CodecCapabilities.<init>(MediaCodecInfo.java:915)
        at android.media.MediaCodecInfo$CodecCapabilities.<init>(MediaCodecInfo.java:866)
        at android.media.MediaCodecList.getCodecCapabilities(Native Method)
        at android.media.MediaCodecList.getNewCodecInfoAt(MediaCodecList.java:111)
        at android.media.MediaCodecList.initCodecList(MediaCodecList.java:87)
        at android.media.MediaCodecList.<init>(MediaCodecList.java:170)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.ensureMediaCodecInfosInitialized(MediaCodecUtil.java:589)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.getCodecCount(MediaCodecUtil.java:567)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:239)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:150)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:126)
        at com.google.android.exoplayer2.mediacodec.MediaCodecSelector$1.getDecoderInfo(MediaCodecSelector.java:34)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.supportsFormat(MediaCodecVideoRenderer.java:239)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:300)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:439)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:345)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:162)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:143)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1507)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)
08-27 22:17:50.813 6148-6179/com.jarvanmo.demo E/MediaCodecList: Could not get codec capabilities
    java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at android.media.MediaCodecInfo$CodecCapabilities.<init>(MediaCodecInfo.java:915)
        at android.media.MediaCodecInfo$CodecCapabilities.<init>(MediaCodecInfo.java:866)
        at android.media.MediaCodecList.getCodecCapabilities(Native Method)
        at android.media.MediaCodecList.getNewCodecInfoAt(MediaCodecList.java:111)
        at android.media.MediaCodecList.initCodecList(MediaCodecList.java:87)
        at android.media.MediaCodecList.<init>(MediaCodecList.java:170)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.ensureMediaCodecInfosInitialized(MediaCodecUtil.java:589)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.getCodecCount(MediaCodecUtil.java:567)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:239)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:150)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:126)
        at com.google.android.exoplayer2.mediacodec.MediaCodecSelector$1.getDecoderInfo(MediaCodecSelector.java:34)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.supportsFormat(MediaCodecVideoRenderer.java:239)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:300)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:439)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:345)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:162)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:143)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1507)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)
08-27 22:17:50.816 6148-6179/com.jarvanmo.demo E/MediaCodecList: Could not get codec capabilities
    java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at android.media.MediaCodecInfo$CodecCapabilities.<init>(MediaCodecInfo.java:915)
        at android.media.MediaCodecInfo$CodecCapabilities.<init>(MediaCodecInfo.java:866)
        at android.media.MediaCodecList.getCodecCapabilities(Native Method)
        at android.media.MediaCodecList.getNewCodecInfoAt(MediaCodecList.java:111)
        at android.media.MediaCodecList.initCodecList(MediaCodecList.java:87)
        at android.media.MediaCodecList.<init>(MediaCodecList.java:170)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.ensureMediaCodecInfosInitialized(MediaCodecUtil.java:589)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.getCodecCount(MediaCodecUtil.java:567)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:239)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:150)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:126)
        at com.google.android.exoplayer2.mediacodec.MediaCodecSelector$1.getDecoderInfo(MediaCodecSelector.java:34)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.supportsFormat(MediaCodecVideoRenderer.java:239)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:300)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:439)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:345)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:162)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:143)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1507)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)
08-27 22:17:50.820 6148-6179/com.jarvanmo.demo E/MediaCodecList: Could not get codec capabilities
    java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at android.media.MediaCodecInfo$CodecCapabilities.<init>(MediaCodecInfo.java:915)
        at android.media.MediaCodecInfo$CodecCapabilities.<init>(MediaCodecInfo.java:866)
        at android.media.MediaCodecList.getCodecCapabilities(Native Method)
        at android.media.MediaCodecList.getNewCodecInfoAt(MediaCodecList.java:111)
        at android.media.MediaCodecList.initCodecList(MediaCodecList.java:87)
        at android.media.MediaCodecList.<init>(MediaCodecList.java:170)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.ensureMediaCodecInfosInitialized(MediaCodecUtil.java:589)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.getCodecCount(MediaCodecUtil.java:567)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:239)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:150)
        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:126)
        at com.google.android.exoplayer2.mediacodec.MediaCodecSelector$1.getDecoderInfo(MediaCodecSelector.java:34)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.supportsFormat(MediaCodecVideoRenderer.java:239)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:300)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:439)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:345)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:162)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:143)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1507)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)
08-27 22:17:50.931 6148-6231/com.jarvanmo.demo E/ACodec: cannot find aac bit rate
08-27 22:17:54.540 6148-6225/? E/ACodec: new surface holds onto more buffers (2) than planned for (1)
08-27 22:17:54.541 6148-6179/? E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1914)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:915)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:405)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:372)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:861)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:829)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:811)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:328)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by JarvanMo** [comment]
这个问题，待我查证一下。我目前还没遇到这个问题。
