### ISSUE TITLE
Error inflating class com.jarvanmo.exoplayerview.ui.ExoVideoView

### ISSUE THREAD

**Issue by WaqasAzamKml** [JarvanMo/ExoPlayerVideoView#9]
I just added gradle dependency, then added the ExoVideoView in my layout file and properly handled its working in the Java section. But this exception comes when I launch the activity that contains ExoVideoView.

```
Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class com.jarvanmo.exoplayerview.ui.ExoVideoView
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:289)
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                       at com.dozydroid.fmp.activities.VideoPlayerActivity.onCreate(VideoPlayerActivity.java:197)
                                                                       at android.app.Activity.performCreate(Activity.java:5343)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
```

Here's peek from my `build.gradle`

```
compile 'com.google.android.exoplayer:exoplayer:r2.5.4'
compile 'com.jarvanmo:exoplayerview:1.1.0'
compile 'com.android.support:cardview-v7:26.+'
compile 'com.android.support:support-v4:26.+'
testCompile 'junit:junit:4.12'
```

My `layout.xml` file:

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:keepScreenOn="true"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="#000"
    tools:context=".activities.VideoPlayerActivity">

    <com.jarvanmo.exoplayerview.ui.ExoVideoView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/player_view"
        app:resize_mode="fit"/>
</RelativeLayout>
```

My `Activity.java` file:

```
private ExoVideoView exoVideoView;
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        exoVideoView = (ExoVideoView) findViewById(R.id.player_view);
        exoVideoView.setPlayer(exoPlayer);
}
```

**Comment by JarvanMo** [comment]
@WaqasAzamKml I've ran the code above several times,it seems nothing wrong.Could you  provide more information,such as os version or the model of your device ?

**Comment by WaqasAzamKml** [comment]
@JarvanMo I'm using Android Studio v3.0 and my phone is Haier i70 which is currently running Android Version 4.4.2 (KitKat).

**Comment by WaqasAzamKml** [comment]
@JarvanMo can you provide any sample app, that includes this (ExoPlayerVideoView) library?

**Comment by JarvanMo** [comment]
@WaqasAzamKml you can checkout this project with:
```
git clone git@github.com:JarvanMo/ExoPlayerVideoView.git
```
then run app,that's the sample.

**Comment by WaqasAzamKml** [comment]
@JarvanMo this sample app ran all-right. I just had to change `compileSdkVersion` to 26 because I don't have the files for **version 27**.
But the library still doesn't work. Any suggestions?

**Comment by JarvanMo** [comment]
What about using this library directly?

**Comment by WaqasAzamKml** [comment]
@JarvanMo what did you mean by "using library directly". Sorry, I didn't understand.

**Comment by WaqasAzamKml** [comment]
Hey @JarvanMo ! I figured out that the problem I'm facing was due to using custom `exo_playback_control_view.xml` file. Since my **control_view** file didn't match the controls defined and used in your library's `ExoPlaybackControlView.java`, the app was unable to run.
But the question now is, how can I use my custom controller with your library?

**Comment by WaqasAzamKml** [comment]
@JarvanMo kindly respond to this ASAP! Because my project relies on this.

**Comment by JarvanMo** [comment]
@WaqasAzamKml Sorry,a little busy these days.This library doesn't support custom `exo_playback_control_view.xml` via gradle in current version.That's what I plan to do in the next version based `exo-2.6.x`.If you want define a custom controller, you should checkout this project ,and then rewrite the files by yourself.

**Comment by WaqasAzamKml** [comment]
@JarvanMo okay last thing. I wasn't able to figure out why videoView sticks to the top? I mean, when controller is visible, video is shown in the middle of the screen (where it should be) but when controller hides, it jumps to the top of screen (this is not good).

**Comment by JarvanMo** [comment]
@WaqasAzamKml  try ``1.1.4``.

**Comment by WaqasAzamKml** [comment]
Okay @JarvanMo does it support custom controller?

**Comment by JarvanMo** [comment]
@WaqasAzamKml not yet.

**Comment by WaqasAzamKml** [comment]
Okay then respectfully Mr. @JarvanMo , what's the difference between `1.1.0` and `1.1.4` ?

**Comment by JarvanMo** [comment]
@WaqasAzamKml not much difference,such as using ```ApplicationContext``` instead fo  ```Contetx``` to get ```AudioManager```,fix bug you mentioned above.

**Comment by JarvanMo** [comment]
forgot to publish`1.1.4`.Now it's released.

**Comment by JarvanMo** [comment]
2.0.0 has been released.
